ARDUINO_DIR	= /usr/share/arduino
BOARD_TAG	= uno
F_CPU		= 8000000L
VARIANT		= atmega328pb
ISP_PORT	= /dev/gpiomem
ISP_PROG	= linuxgpio
AVRDUDE_MCU	= atmega328pb

include /usr/share/arduino/Arduino.mk
